<?php

namespace Workdo\Portfolio\Database\Seeders;

use Workdo\Portfolio\Models\Portfolio;
use Illuminate\Database\Seeder;
use Workdo\Portfolio\Models\PortfolioCategory;


class DemoPortfolioSeeder extends Seeder
{
    public function run($userId): void
    {
        if (Portfolio::where('created_by', $userId)->exists()) {
            return;
        }

        $portfolios = [
            [
                'title'            => 'E-Commerce Platform',
                'description'      => 'A modern e-commerce platform with advanced features',
                'slug'             => 'e-commerce-platform',
                'overview'         => '<p>Built a comprehensive e-commerce platform with user authentication, payment integration, and admin dashboard. Features include product catalog, shopping cart, order management, and analytics.</p>',
                'name'             => 'John Developer',
                'role'             => 'Full Stack Developer',
                'experience_years' => '5.5',
                'photo'            => 'profile1.jpg',
                'email'            => 'john@example.com',
                'education'        => 'Computer Science, MIT',
                'live_url'         => 'https://demo-ecommerce.com',
                'repository_url'   => 'https://github.com/john/ecommerce',
                'skills'           => ['React', 'Node.js', 'MongoDB', 'Stripe', 'AWS'],
                'client'           => 'TechCorp Inc.',
                'duration'         => '6 months',
                'team_size'        => 4,
                'start_date'       => '2023-01-15',
                'end_date'         => '2023-07-15',
                'budget'           => '$45,000 - $55,000',
                'industry'         => 'E-commerce',
                'images'           => ['ecommerce1.jpg', 'ecommerce2.jpg'],
                'video_link'       => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'show_overview'    => true,
                'show_gallery'     => true,
                'show_contact'     => true,
                'contact_heading'  => 'Ready to build your e-commerce solution?',
                'contact_message'  => 'Let\'s discuss your online store requirements and create something amazing together.',
            ],
            [
                'title'            => 'Mobile Banking App',
                'description'      => 'Secure mobile banking application with biometric authentication',
                'slug'             => 'mobile-banking-app',
                'overview'         => '<p>Developed a secure mobile banking application with features like account management, fund transfers, bill payments, and investment tracking. Implemented advanced security measures including biometric authentication.</p>',
                'name'             => 'Sarah Johnson',
                'role'             => 'Mobile App Developer',
                'experience_years' => '7.2',
                'photo'            => 'profile2.jpg',
                'email'            => 'sarah@example.com',
                'education'        => 'Software Engineering, Stanford',
                'live_url'         => 'https://apps.apple.com/banking-app',
                'repository_url'   => 'https://github.com/sarah/banking-app',
                'skills'           => ['React Native', 'Firebase', 'TypeScript', 'Biometric API', 'Redux'],
                'client'           => 'SecureBank Ltd.',
                'duration'         => '8 months',
                'team_size'        => 6,
                'start_date'       => '2022-09-01',
                'end_date'         => '2023-05-01',
                'budget'           => '$120,000 - $130,000',
                'industry'         => 'Financial Services',
                'images'           => [],
                'video_link'       => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'show_overview'    => true,
                'show_gallery'     => false,
                'show_contact'     => true,
                'contact_heading'  => 'Need a secure mobile app?',
                'contact_message'  => 'I specialize in building secure, user-friendly mobile applications for financial services.',
            ],
            [
                'title'            => 'AI-Powered Analytics Dashboard',
                'description'      => 'Real-time analytics dashboard with machine learning insights',
                'slug'             => 'ai-analytics-dashboard',
                'overview'         => '<p>Created an intelligent analytics dashboard that processes large datasets and provides AI-powered insights. Features real-time data visualization, predictive analytics, and automated reporting.</p>',
                'name'             => 'Mike Chen',
                'role'             => 'Data Engineer',
                'experience_years' => '6.8',
                'photo'            => 'profile3.jpg',
                'email'            => 'mike@example.com',
                'education'        => 'Data Science, UC Berkeley',
                'live_url'         => 'https://analytics-demo.com',
                'repository_url'   => 'https://github.com/mike/ai-dashboard',
                'skills'           => ['Python', 'TensorFlow', 'React', 'PostgreSQL', 'Docker', 'Kubernetes'],
                'client'           => 'DataTech Solutions',
                'duration'         => '10 months',
                'team_size'        => 5,
                'start_date'       => '2022-06-01',
                'end_date'         => '2023-04-01',
                'budget'           => '$80,000 - $90,000',
                'industry'         => 'Technology',
                'images'           => [],
                'video_link'       => null,
                'show_overview'    => true,
                'show_gallery'     => false,
                'show_contact'     => true,
                'contact_heading'  => 'Transform your data into insights',
                'contact_message'  => 'Let me help you build powerful analytics solutions that drive business decisions.',
            ],
            [
                'title'            => 'Healthcare Management System',
                'description'      => 'Comprehensive healthcare management platform for hospitals',
                'slug'             => 'healthcare-management-system',
                'overview'         => '<p>Developed a complete healthcare management system for hospitals including patient records, appointment scheduling, billing, and staff management. Ensures HIPAA compliance and data security.</p>',
                'name'             => 'Dr. Emily Rodriguez',
                'role'             => 'Healthcare IT Specialist',
                'experience_years' => '8.3',
                'photo'            => 'profile4.jpg',
                'email'            => 'emily@example.com',
                'education'        => 'Medical Informatics, Johns Hopkins',
                'live_url'         => 'https://healthcare-demo.com',
                'repository_url'   => 'https://github.com/emily/healthcare-system',
                'skills'           => ['Vue.js', 'Laravel', 'MySQL', 'HIPAA Compliance', 'HL7 FHIR'],
                'client'           => 'Metropolitan Hospital',
                'duration'         => '12 months',
                'team_size'        => 8,
                'start_date'       => '2022-01-01',
                'end_date'         => '2023-01-01',
                'budget'           => '$180,000 - $220,000',
                'industry'         => 'Healthcare',
                'images'           => [],
                'video_link'       => null,
                'show_overview'    => true,
                'show_gallery'     => false,
                'show_contact'     => true,
                'contact_heading'  => 'Modernize your healthcare systems',
                'contact_message'  => 'I help healthcare organizations implement secure, compliant digital solutions.',
            ],
            [
                'title'            => 'Social Media Marketing Tool',
                'description'      => 'All-in-one social media management and analytics platform',
                'slug'             => 'social-media-marketing-tool',
                'overview'         => '<p>Built a comprehensive social media management platform that allows users to schedule posts, analyze engagement, track competitors, and generate detailed reports across multiple social platforms.</p>',
                'name'             => 'Alex Thompson',
                'role'             => 'Frontend Developer',
                'experience_years' => '4.7',
                'photo'            => 'profile5.jpg',
                'email'            => 'alex@example.com',
                'education'        => 'Web Development, FreeCodeCamp',
                'live_url'         => 'https://socialtool-demo.com',
                'repository_url'   => 'https://github.com/alex/social-tool',
                'skills'           => ['Angular', 'Express.js', 'Redis', 'Social APIs', 'Chart.js'],
                'client'           => 'Marketing Pro Agency',
                'duration'         => '5 months',
                'team_size'        => 3,
                'start_date'       => '2023-03-01',
                'end_date'         => '2023-08-01',
                'budget'           => '$30,000 - $40,000',
                'industry'         => 'Digital Marketing',
                'images'           => ['social1.jpg', 'social2.jpg'],
                'video_link'       => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'show_overview'    => true,
                'show_gallery'     => true,
                'show_contact'     => true,
                'contact_heading'  => 'Boost your social media presence',
                'contact_message'  => 'Let\'s create powerful tools that help businesses succeed on social media.',
            ],
            [
                'title'            => 'Restaurant Management System',
                'description'      => 'Complete restaurant POS and management solution',
                'slug'             => 'restaurant-management-system',
                'overview'         => '<p>Developed a comprehensive restaurant management system with POS, inventory tracking, staff scheduling, and customer management. Includes online ordering and delivery integration.</p>',
                'name'             => 'David Kumar',
                'role'             => 'Backend Developer',
                'experience_years' => '5.3',
                'photo'            => 'profile6.jpg',
                'email'            => 'david@example.com',
                'education'        => 'Computer Engineering, IIT Delhi',
                'live_url'         => 'https://restaurant-demo.com',
                'repository_url'   => 'https://github.com/david/restaurant-pos',
                'skills'           => ['PHP', 'Laravel', 'MySQL', 'Vue.js', 'Payment APIs'],
                'client'           => 'FoodChain Restaurants',
                'duration'         => '7 months',
                'team_size'        => 4,
                'start_date'       => '2023-02-01',
                'end_date'         => '2023-09-01',
                'budget'           => '$60,000 - $70,000',
                'industry'         => 'Food & Beverage',
                'images'           => ['restaurant1.jpg', 'restaurant2.jpg', 'restaurant3.jpg'],
                'video_link'       => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'show_overview'    => true,
                'show_gallery'     => true,
                'show_contact'     => true,
                'contact_heading'  => 'Streamline your restaurant operations',
                'contact_message'  => 'Let me help you build efficient restaurant management solutions.',
            ],
            [
                'title'            => 'Real Estate CRM Platform',
                'description'      => 'Advanced CRM system for real estate agencies',
                'slug'             => 'real-estate-crm-platform',
                'overview'         => '<p>Built a powerful CRM platform for real estate agencies with lead management, property listings, client tracking, and automated marketing campaigns. Includes mobile app for agents.</p>',
                'name'             => 'Lisa Wang',
                'role'             => 'Full Stack Developer',
                'experience_years' => '6.1',
                'photo'            => 'profile7.jpg',
                'email'            => 'lisa@example.com',
                'education'        => 'Software Development, University of Toronto',
                'live_url'         => 'https://realestate-crm.com',
                'repository_url'   => 'https://github.com/lisa/realestate-crm',
                'skills'           => ['Django', 'React', 'PostgreSQL', 'Redis', 'AWS S3'],
                'client'           => 'Prime Properties Ltd.',
                'duration'         => '9 months',
                'team_size'        => 5,
                'start_date'       => '2022-08-01',
                'end_date'         => '2023-05-01',
                'budget'           => '$90,000 - $100,000',
                'industry'         => 'Real Estate',
                'images'           => [],
                'video_link'       => null,
                'show_overview'    => true,
                'show_gallery'     => false,
                'show_contact'     => true,
                'contact_heading'  => 'Boost your real estate business',
                'contact_message'  => 'Transform your real estate operations with custom CRM solutions.',
            ],
            [
                'title'            => 'Learning Management System',
                'description'      => 'Online education platform with interactive features',
                'slug'             => 'learning-management-system',
                'overview'         => '<p>Created a comprehensive LMS with course creation, student enrollment, progress tracking, quizzes, and video streaming. Supports multiple learning formats and certification.</p>',
                'name'             => 'Robert Martinez',
                'role'             => 'EdTech Developer',
                'experience_years' => '7',
                'photo'            => 'profile8.jpg',
                'email'            => 'robert@example.com',
                'education'        => 'Educational Technology, Harvard',
                'live_url'         => 'https://lms-demo.com',
                'repository_url'   => 'https://github.com/robert/lms-platform',
                'skills'           => ['Next.js', 'Node.js', 'MongoDB', 'Socket.io', 'FFmpeg'],
                'client'           => 'EduTech Academy',
                'duration'         => '11 months',
                'team_size'        => 6,
                'start_date'       => '2022-05-01',
                'end_date'         => '2023-04-01',
                'budget'           => '$110,000',
                'industry'         => 'Education',
                'images'           => ['lms1.jpg', 'lms2.jpg'],
                'video_link'       => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'show_overview'    => true,
                'show_gallery'     => true,
                'show_contact'     => true,
                'contact_heading'  => 'Revolutionize online learning',
                'contact_message'  => 'Let\'s build engaging educational platforms that inspire learning.',
            ],
            [
                'title'            => 'Fitness Tracking Mobile App',
                'description'      => 'Comprehensive fitness and wellness tracking application',
                'slug'             => 'fitness-tracking-mobile-app',
                'overview'         => '<p>Developed a feature-rich fitness app with workout tracking, nutrition logging, progress analytics, and social features. Integrates with wearable devices and health APIs.</p>',
                'name'             => 'Jessica Brown',
                'role'             => 'Mobile Developer',
                'experience_years' => '4',
                'photo'            => 'profile9.jpg',
                'email'            => 'jessica@example.com',
                'education'        => 'Mobile App Development, Georgia Tech',
                'live_url'         => 'https://apps.apple.com/fitness-tracker',
                'repository_url'   => 'https://github.com/jessica/fitness-app',
                'skills'           => ['Flutter', 'Dart', 'Firebase', 'HealthKit', 'Google Fit'],
                'client'           => 'FitLife Solutions',
                'duration'         => '6 months',
                'team_size'        => 3,
                'start_date'       => '2023-04-01',
                'end_date'         => '2023-10-01',
                'budget'           => '$45,000',
                'industry'         => 'Health & Fitness',
                'images'           => [],
                'video_link'       => null,
                'show_overview'    => true,
                'show_gallery'     => false,
                'show_contact'     => true,
                'contact_heading'  => 'Build your fitness empire',
                'contact_message'  => 'Create powerful fitness apps that motivate and engage users.',
            ],
            [
                'title'            => 'Inventory Management System',
                'description'      => 'Smart inventory and warehouse management solution',
                'slug'             => 'inventory-management-system',
                'overview'         => '<p>Built an intelligent inventory management system with barcode scanning, automated reordering, supplier management, and real-time stock tracking across multiple warehouses.</p>',
                'name'             => 'Michael Singh',
                'role'             => 'Systems Developer',
                'experience_years' => '9',
                'photo'            => 'profile10.jpg',
                'email'            => 'michael@example.com',
                'education'        => 'Information Systems, University of Melbourne',
                'live_url'         => 'https://inventory-demo.com',
                'repository_url'   => 'https://github.com/michael/inventory-system',
                'skills'           => ['C#', '.NET Core', 'SQL Server', 'Angular', 'Azure'],
                'client'           => 'LogiCorp Warehouses',
                'duration'         => '8 months',
                'team_size'        => 4,
                'start_date'       => '2022-10-01',
                'end_date'         => '2023-06-01',
                'budget'           => '$70,000 - $80,000',
                'industry'         => 'Logistics',
                'images'           => ['inventory1.jpg', 'inventory2.jpg'],
                'video_link'       => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'show_overview'    => true,
                'show_gallery'     => true,
                'show_contact'     => true,
                'contact_heading'  => 'Optimize your inventory operations',
                'contact_message'  => 'Streamline your warehouse operations with smart inventory solutions.',
            ],
        ];

        foreach ($portfolios as $portfolioData) {
            $portfolio = Portfolio::create([
                'title'            => $portfolioData['title'],
                'description'      => $portfolioData['description'],
                'slug'             => $portfolioData['slug'],
                'overview'         => $portfolioData['overview'],
                'name'             => $portfolioData['name'],
                'role'             => $portfolioData['role'],
                'experience_years' => $portfolioData['experience_years'],
                'photo'            => $portfolioData['photo'],
                'email'            => $portfolioData['email'],
                'education'        => $portfolioData['education'],
                'live_url'         => $portfolioData['live_url'],
                'repository_url'   => $portfolioData['repository_url'],
                'skills'           => $portfolioData['skills'],
                'client'           => $portfolioData['client'],
                'duration'         => $portfolioData['duration'],
                'team_size'        => $portfolioData['team_size'],
                'start_date'       => $portfolioData['start_date'],
                'end_date'         => $portfolioData['end_date'],
                'budget'           => $portfolioData['budget'],
                'industry'         => $portfolioData['industry'],
                'images'           => $portfolioData['images'],
                'video_link'       => $portfolioData['video_link'],
                'show_overview'    => $portfolioData['show_overview'],
                'show_gallery'     => $portfolioData['show_gallery'],
                'show_contact'     => $portfolioData['show_contact'],
                'contact_heading'  => $portfolioData['contact_heading'],
                'contact_message'  => $portfolioData['contact_message'],
                'category_id'      => PortfolioCategory::where('created_by', $userId)->where('is_active', 1)->inRandomOrder()->first()?->id,
                'creator_id'       => $userId,
                'created_by'       => $userId,
            ]);

            // Add custom sections for some portfolios
            if (in_array($portfolio->slug, ['e-commerce-platform', 'mobile-banking-app'])) {
                $portfolio->custom_sections()->create([
                    'title'      => 'Technical Challenges',
                    'content'    => '<p>This project presented several technical challenges including scalability, security, and user experience optimization. We implemented advanced caching strategies and microservices architecture to handle high traffic loads.</p>',
                    'sort_order' => 0
                ]);

                $portfolio->custom_sections()->create([
                    'title'      => 'Results & Impact',
                    'content'    => '<p>The solution resulted in a 40% increase in user engagement and 25% improvement in conversion rates. The client reported significant cost savings and improved operational efficiency.</p>',
                    'sort_order' => 1
                ]);
            }
        }
    }
}
